server:
  port: 8081
  servlet:
    context-path: /api
  error:
    include-message: always

spring:
  application:
    name: product-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/nab_product
    username: postgres
    password: 2020
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 10
      auto-commit: false
      pool-name: Hikari

logging:
  level:
    com.nab.assignment.product: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug

application:
  name: @project.name@
  version: @project.version@
  description: @project.description@